version: '3.8'
include:
  - compose.monitoring.yml
services:
  backend:
    build:
      context: ./backend
    container_name: fastapi_app
    ports:
      - "8000:8000"
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - db
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    container_name: nodejs_app
    ports:
      - "5173:5173"
    networks:
      - frontend-network
    env_file:
      - ./frontend/.env
    
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: app
      POSTGRES_DB: app
    secrets:
      - postgres_password
    networks:
      - backend-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    networks:
      - backend-network

  proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx_proxy_manager
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
      - backend
      - frontend
      - adminer
    networks:
      - frontend-network
      - backend-network
      
networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
 
volumes:
  postgres_data:
  data:
  letsencrypt:

secrets:
   postgres_password:
     file: ./POSTGRES_PASSWORD.txt
